#!/bin/bash
# Manual execution guide for comprehensive fix
# This provides individual commands that can be executed with proper sudo access

echo "=== Speed4You Scanner Comprehensive Fix (Manual Execution Guide) ==="
echo ""
echo "Please execute the following commands step by step:"
echo ""
echo "STEP 1: Fix Permission Structure"
echo "--------------------------------"
echo "sudo chown -R www-data:www-data /var/www/html/Requested/"
echo "sudo chmod -R 755 /var/www/html/Requested/"
echo ""

echo "STEP 2: Update Scanner Configuration"
echo "--------------------------------------"
echo "cat >> /home/speed4you/portal-app/backend/.env << EOF"
echo "SCANNER_MIN_MOVIE_SIZE=52428800"
echo "SCANNER_MIN_EPISODE_SIZE=52428800"
echo "SCANNER_AUTO_SCAN_INTERVAL_MINUTES=360"
echo "EOF"
echo ""

echo "STEP 3: Fix File Naming Issues"
echo "--------------------------------"
echo "mv '/var/www/html/Requested/Series/Musafir Cafe (2026)/S1/Musafir.Cafe.S01E01.720p..mkv' \\"
echo "   '/var/www/html/Requested/Series/Musafir Cafe (2026)/S1/Musafir.Cafe.S01E01.720p.mkv'"
echo ""

echo "STEP 4: Publish Valid Draft Items"
echo "-----------------------------------"
echo "psql -U postgres -d isp_entertainment -c \""
echo "UPDATE content_catalog "
echo "SET status = 'published' "
echo "WHERE source_root_id = 'south-indian-movies' "
echo "  AND status = 'draft' "
echo "  AND title NOT LIKE '%p'"
echo "  AND poster IS NOT NULL"
echo "  AND backdrop IS NOT NULL"
echo "  AND description IS NOT NULL;"
echo "\""
echo ""

echo "STEP 5: Setup Permission Monitoring"
echo "-----------------------------------"
echo "cat > /home/speed4you/monitor-permissions.sh << 'MONITOR_EOF'"
echo "#!/bin/bash"
echo "CHECK_DIR=\"/var/www/html/Requested\""
echo "LOG_FILE=\"/var/log/permission-monitor.log\""
echo ""
echo "if [ \"\$(stat -c %U:%G \"\$CHECK_DIR\")\" != \"www-data:www-data\" ]; then"
echo "  echo \"\$(date): Fixing permissions for \$CHECK_DIR\" >> \"\$LOG_FILE\""
echo "  sudo chown -R www-data:www-data \"\$CHECK_DIR\""
echo "  sudo chmod -R 755 \"\$CHECK_DIR\""
echo "  echo \"\$(date): Permissions fixed\" >> \"\$LOG_FILE\""
echo "fi"
echo "MONITOR_EOF"
echo ""
echo "chmod +x /home/speed4you/monitor-permissions.sh"
echo "(crontab -l 2>/dev/null; echo '0 2 * * * /home/speed4you/monitor-permissions.sh >> /var/log/permission-monitor.log 2>&1') | crontab -"
echo ""

echo "STEP 6: Create Upload Guidelines"
echo "-----------------------------------"
echo "cat > /var/www/html/UPLOAD_GUIDELINES.md << 'GUIDELINES_EOF'"
echo "# Speed4You Upload Guidelines"
echo ""
echo "## File Naming Requirements"
echo "- Use standard naming: SeriesName.S01E01.720p.mkv (no double dots)"
echo "- Avoid special characters in filenames"
echo "- Use proper season/episode numbering"
echo ""
echo "## Directory Structure"
echo "- Series: /Requested/Series/Series Name (Year)/S01/"
echo "- Movies: /Requested/Movies/Movie Name (Year).mkv"
echo ""
echo "## Permission Requirements"
echo "- All files should be owned by www-data:www-data"
echo "- Directories should have 755 permissions"
echo "- Files should have 644 permissions"
echo ""
echo "## Content Requirements"
echo "- Minimum file size: 50MB"
echo "- Valid video formats: .mkv, .mp4, .avi, .mov"
echo "- Include poster images when possible"
echo ""
echo "## Scanner Processing"
echo "- Scanner runs every 6 hours automatically"
echo "- New content is typically processed within 6 hours of upload"
echo "- Draft items are published automatically once metadata is complete"
echo "GUIDELINES_EOF"
echo ""

echo "STEP 7: Trigger Comprehensive Rescan"
echo "-------------------------------------"
echo "WEBHOOK_SECRET=\$(grep 'WEBHOOK_SECRET' /home/speed4you/portal-app/backend/.env | cut -d '=' -f2)"
echo "curl -X POST https://data.speed4you.net/portal-api/api/webhook/scan \\"
echo "  -H \"x-webhook-secret: \$WEBHOOK_SECRET\" \\"
echo "  -H \"Content-Type: application/json\""
echo ""

echo "STEP 8: Restart Backend Service"
echo "---------------------------------"
echo "sudo systemctl restart isp-portal.service"
echo "sudo systemctl status isp-portal.service"
echo ""

echo "=== Manual Execution Guide Complete ==="
echo "Copy and execute each command group step by step"
