server {
    listen 443 ssl http2;
    server_name data.speed4you.net;

    ssl_certificate CERT_PH;
    ssl_certificate_key KEY_PH;

    root /var/www/html/data;
    index index.html index.php /_h5ai/public/index.php;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        try_files $uri $uri/ /_h5ai/public/index.php$is_args$args;
    }

    location ~ ^/_h5ai/private/ {
        deny all;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass SOCK_PH;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
