#!/usr/bin/env node
/**
 * setup-***REMOVED***s.cjs
 *
 * Reads ***REMOVED***s from ***REMOVED***s/local/ and installs them in the right places:
 *   - ***REMOVED***s/local/.env          -> backend/.env
 *                                   -> frontend/.env.local (VITE_* keys only)
 *   - ***REMOVED***s/local/deploy_key    -> ./deploy_key           (chmod 600)
 *   - ***REMOVED***s/local/deploy_key.pub-> ./deploy_key.pub
 *
 * The script NEVER prints a ***REMOVED*** value. It only logs the names of the
 * variables / files it installed.
 *
 * Backward compatible: if ***REMOVED***s/local/ is empty, the script falls back
 * to any .env / deploy_key that already exists at the project root. Nothing
 * is overwritten without an explicit --force flag.
 *
 * Usage:
 *   node scripts/setup-***REMOVED***s.cjs           # install (default)
 *   node scripts/setup-***REMOVED***s.cjs --dry     # show what would happen, change nothing
 *   node scripts/setup-***REMOVED***s.cjs --force   # overwrite existing target files
 *   node scripts/setup-***REMOVED***s.cjs --help
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const SECRETS = path.join(ROOT, '***REMOVED***s', 'local');
const args = new Set(process.argv.slice(2));
const dry = args.has('--dry') || args.has('-n');
const force = args.has('--force') || args.has('-f');

if (args.has('--help') || args.has('-h')) {
  console.log([
    'Usage: node scripts/setup-***REMOVED***s.cjs [options]',
    '',
    'Options:',
    '  --dry, -n    Show what would happen; change nothing',
    '  --force, -f  Overwrite existing target files (default: refuse)',
    '  --help, -h   Show this help',
    '',
    'Sources (highest priority first):',
    '  ***REMOVED***s/local/.env',
    '  ***REMOVED***s/local/deploy_key',
    '  ***REMOVED***s/local/deploy_key.pub',
    '  (fallback) .env / .env.deploy / deploy_key at project root',
  ].join('\n'));
  process.exit(0);
}

const log = (msg) => console.log(`  ${msg}`);
const warn = (msg) => console.log(`  ! ${msg}`);
const err = (msg) => console.log(`  \u2717 ${msg}`);

function exists(p) { try { fs.accessSync(p); return true; } catch { return false; } }
function readSafe(p) { try { return fs.readFileSync(p, 'utf8'); } catch { return null; } }

function readEnvFile(p) {
  if (!exists(p)) return null;
  const text = readSafe(p);
  if (text === null) return null;
  const out = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function writeEnvFile(p, envObj, { overwrite }) {
  if (exists(p) && !overwrite) return { written: false, reason: 'target exists (use --force to overwrite)' };
  const lines = [];
  lines.push('# Generated by scripts/setup-***REMOVED***s.cjs on ' + new Date().toISOString());
  lines.push('# Source: ***REMOVED***s/local/.env  (do not edit this file directly; edit the source)');
  lines.push('');
  const keys = Object.keys(envObj).sort();
  for (const k of keys) {
    const v = envObj[k];
    if (v == null || v === '') continue;
    if (/[ "'#\n\r]/.test(v)) {
      lines.push(`${k}="${v.replace(/"/g, '\\"')}"`);
    } else {
      lines.push(`${k}=${v}`);
    }
  }
  if (dry) return { written: false, reason: '--dry' };
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, lines.join('\n') + '\n', { encoding: 'utf8', mode: 0o600 });
  return { written: true };
}

function copyKeyFile(src, dest, { overwrite }) {
  if (!exists(src)) return { copied: false, reason: 'source missing' };
  if (exists(dest) && !overwrite) return { copied: false, reason: 'target exists (use --force)' };
  if (dry) return { copied: false, reason: '--dry' };
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
  try { fs.chmodSync(dest, 0o600); } catch { /* icacls below covers Windows */ }
  return { copied: true };
}

function tightenPerms(p) {
  if (dry || !exists(p)) return;
  if (process.platform === 'win32') {
    try {
      execSync(`icacls "${p}" /inheritance:r /grant:r "%USERNAME%:(R)" /remove:g "Authenticated Users" "BUILTIN\\Users" "Everyone"`, { stdio: 'ignore' });
    } catch { /* best effort */ }
  } else {
    try { fs.chmodSync(p, 0o600); } catch { /* best effort */ }
  }
}

console.log(`Speed4You ***REMOVED***s setup ${dry ? '(dry run) ' : ''}`);
console.log('----------------------------------------');

let masterEnv = readEnvFile(path.join(SECRETS, '.env'));
let masterSource = path.join(SECRETS, '.env');
if (!masterEnv) {
  masterEnv = readEnvFile(path.join(ROOT, '.env')) || readEnvFile(path.join(ROOT, '.env.deploy'));
  masterSource = masterEnv ? path.join(ROOT, '.env') : null;
}
if (masterEnv) {
  log(`master .env: ${path.relative(ROOT, masterSource)}  (${Object.keys(masterEnv).length} keys)`);
} else {
  warn('no .env found at ***REMOVED***s/local/.env or project root — backend will start with missing config');
}

const backendEnvPath = path.join(ROOT, 'backend', '.env');
if (masterEnv) {
  const r = writeEnvFile(backendEnvPath, masterEnv, { overwrite: force });
  if (r.written) log(`wrote backend/.env (${Object.keys(masterEnv).length} vars)`);
  else warn(`backend/.env: ${r.reason}`);
}

const frontendEnvPath = path.join(ROOT, 'frontend', '.env.local');
if (masterEnv) {
  const viteKeys = Object.fromEntries(Object.entries(masterEnv).filter(([k]) => k.startsWith('VITE_')));
  if (Object.keys(viteKeys).length) {
    const r = writeEnvFile(frontendEnvPath, viteKeys, { overwrite: force });
    if (r.written) log(`wrote frontend/.env.local (${Object.keys(viteKeys).length} VITE_ vars)`);
    else warn(`frontend/.env.local: ${r.reason}`);
  } else {
    log('frontend/.env.local: skipped (no VITE_* keys in master .env)');
  }
}

const keySrc = path.join(SECRETS, 'deploy_key');
const keyDest = path.join(ROOT, 'deploy_key');
if (exists(keySrc)) {
  const r = copyKeyFile(keySrc, keyDest, { overwrite: force });
  if (r.copied) { log('copied deploy_key -> ./deploy_key  (mode 0600)'); tightenPerms(keyDest); }
  else warn(`deploy_key: ${r.reason}`);
} else if (exists(keyDest)) {
  log('deploy_key: keeping existing ./deploy_key (no source in ***REMOVED***s/local/)');
} else {
  warn('deploy_key: missing at ***REMOVED***s/local/deploy_key and ./deploy_key — deploys will fail');
}

const pubSrc = path.join(SECRETS, 'deploy_key.pub');
const pubDest = path.join(ROOT, 'deploy_key.pub');
if (exists(pubSrc)) {
  const r = copyKeyFile(pubSrc, pubDest, { overwrite: force });
  if (r.copied) log('copied deploy_key.pub -> ./deploy_key.pub');
  else warn(`deploy_key.pub: ${r.reason}`);
} else if (exists(pubDest)) {
  log('deploy_key.pub: keeping existing ./deploy_key.pub');
} else {
  warn('deploy_key.pub: missing (not strictly required, but recommended)');
}

console.log('');
console.log(dry ? 'Dry run complete. Re-run without --dry to apply.' : 'Done.');
console.log('Run `npm run ***REMOVED***s:check` to verify everything is in place.');
